version: '2'
services:
    backend:
       build: "backend/"
       restart: always
       depends_on:
         - mongodb
       ports:
         - "9000:80"
       volumes:
         - ./backend/src:/var/www/html
    frontend:
        build: "frontend/"
        depends_on:
         - backend
        ports:
          - 3000:80
    mongodb:
        image: mongo
        container_name: mongo
        restart: always
        volumes:
            - ./data/db/mongo:/data/db
        ports:
            - "27020:27017"
        command: --storageEngine wiredTiger