<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload6ef0ef8b35365a13eff888f9d54a0c49($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'model\\factory\\playerfactory' => '/model/factory/PlayerFactory.php',
            'model\\player' => '/model/Player.php',
            'model\\team' => '/model/Team.php',
            'playercreationtests' => '/tests/PlayerTest.php',
            'services\\datasingleton' => '/services/DataSingleton.php',
            'services\\randomnames' => '/services/RandomNames.php',
            'teamcreationtests' => '/tests/TeamTest.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload6ef0ef8b35365a13eff888f9d54a0c49', true);
// @codeCoverageIgnoreEnd
