<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload4d02665535d4afc1b93870c7d00c61b2($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'controller\\basecontroller' => '/controller/BaseController.php',
            'controller\\teamcontroller' => '/controller/TeamController.php',
            'model\\factory\\playerfactory' => '/model/factory/PlayerFactory.php',
            'model\\factory\\teamfactory' => '/model/factory/TeamFactory.php',
            'model\\player' => '/model/Player.php',
            'model\\team' => '/model/Team.php',
            'playercreationtests' => '/tests/PlayerTest.php',
            'services\\datasingleton' => '/services/DataSingleton.php',
            'services\\mongomanager' => '/services/MongoManager.php',
            'services\\randomnames' => '/services/RandomNames.php',
            'teamcreationtests' => '/tests/TeamTest.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload4d02665535d4afc1b93870c7d00c61b2', true);
// @codeCoverageIgnoreEnd
