<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
function autoload0c0cbd243c33a58c9bb284951d2b7708($class) {
    static $classes = null;
    if ($classes === null) {
        $classes = array(
            'model\\player' => '/model/Player.php',
            'model\\team' => '/model/Team.php'
        );
    }
    $cn = strtolower($class);
    if (isset($classes[$cn])) {
        require dirname(__FILE__) . $classes[$cn];
    }
}
spl_autoload_register('autoload0c0cbd243c33a58c9bb284951d2b7708', true);
// @codeCoverageIgnoreEnd
